import type { AutomationTrigger } from "@prisma/client"

export const automationTriggerLabels: Record<AutomationTrigger, string> = {
  INBOUND_UNKNOWN_CALL: "Appel entrant inconnu",
  INBOUND_CALL_RECEIVED: "Appel entrant reçu",
  CALL_COMPLETED: "Appel complété",
  INBOUND_SMS_RECEIVED: "SMS entrant reçu",
  SMS_FAILED: "Échec SMS",
  LEAD_CREATED: "Prospect créé",
  LEAD_STATUS_CHANGED: "Statut prospect modifié",
  LEAD_CONVERTED: "Prospect converti",
  CLIENT_CREATED: "Client créé",
  CLIENT_UPDATED: "Client modifié",
  CLIENT_NO_CONTACT_90_DAYS: "Client sans suivi 90 jours",
  CLIENT_NO_FOLLOW_UP_90_DAYS: "Client sans suivi 90 jours",
  TASK_CREATED: "Tâche créée",
  TASK_COMPLETED: "Tâche terminée",
  TASK_OVERDUE: "Tâche en retard",
  DOCUMENT_CREATED: "Document créé",
  DOCUMENT_ADDED: "Document ajouté",
  DOCUMENT_STATUS_CHANGED: "Statut document modifié",
  DOCUMENT_EXPIRED: "Document expiré",
  NOTE_ADDED: "Note ajoutée",
  PRODUCT_CREATED: "Produit créé",
  PRODUCT_UPDATED: "Produit modifié",
  PRODUCT_STATUS_CHANGED: "Statut produit modifié",
  PRODUCT_RENEWAL_SOON: "Renouvellement produit proche",
  PRODUCT_REVIEW_DUE: "Révision produit due",
  PRODUCT_REVIEWED: "Produit révisé",
  PRODUCT_ARCHIVED: "Produit archivé",
  KYC_INCOMPLETE: "Profil client incomplet",
  KYC_UPDATED: "Profil client modifié",
  KYC_EXPIRED: "Profil client expiré",
  KYC_APPROVED: "Profil client approuvé",
  CONSENT_REVOKED: "Consentement révoqué",
  COMPLIANCE_ALERT_CREATED: "Alerte conformité créée",
  SMART_ALERT_CREATED: "Alerte intelligente créée",
  ALERT_RESOLVED: "Alerte résolue",
  RECOMMENDATION_CREATED: "Recommandation créée",
  CROSS_SELL_CREATED: "Opportunité créée",
}
