import type {
  Activity,
  AutomationRule,
  Client,
  Communication,
  CrmDocument,
  CrmTask,
  FinancialProduct,
  Lead,
  Notification,
} from "@/types"

export const prospects: Lead[] = [
  {
    id: "antoine-leduc",
    firstName: "Antoine",
    lastName: "Leduc",
    phone: "+1 514 555 0198",
    email: "antoine.leduc@example.ca",
    address: "1280 rue Saint-Denis, Montréal, QC",
    source: "Appel entrant",
    status: "Nouveau",
    interest: "Assurance vie",
    priority: "Urgente",
    advisor: "Marié Lambert",
    nextAction: "Rappeler aujourd’hui avant 16:00",
    createdAt: "2026-04-29",
    lastContact: "2026-05-02",
    notes:
      "Travailleur autonome, souhaite protéger sa conjointe et comparer les primes.",
    tone: "emerald",
  },
  {
    id: "camille-fortin",
    firstName: "Camille",
    lastName: "Fortin",
    phone: "+1 450 555 0142",
    email: "camille.fortin@example.ca",
    address: "44 chemin Chambly, Longueuil, QC",
    source: "Formulaire web",
    status: "Qualifié",
    interest: "REER et CELI",
    priority: "Haute",
    advisor: "Marie Lambert",
    nextAction: "Envoyer une proposition de plan d’épargne",
    createdAt: "2026-04-24",
    lastContact: "2026-05-01",
    notes: "Souhaite optimiser son épargne retraite et ses liquidités à moyen terme.",
    tone: "sky",
  },
  {
    id: "marc-nguyen",
    firstName: "Marc",
    lastName: "Nguyen",
    phone: "+1 438 555 0177",
    email: "marc.nguyen@example.ca",
    address: "730 avenue Laurier Ouest, Montréal, QC",
    source: "Référence",
    status: "À contacter",
    interest: "Assurance invalidité",
    priority: "Normale",
    advisor: "Alex Roy",
    nextAction: "Planifier un appel découverte",
    createdAt: "2026-04-27",
    lastContact: "2026-04-28",
    notes: "Recommandé par un client existant, professionnel en TI.",
    tone: "amber",
  },
  {
    id: "julie-tremblay",
    firstName: "Julie",
    lastName: "Tremblay",
    phone: "+1 418 555 0105",
    email: "julie.tremblay@example.ca",
    address: "92 rue Cartier, Québec, QC",
    source: "Campagne marketing",
    status: "Proposition envoyée",
    interest: "CELI",
    priority: "Basse",
    advisor: "Marie Lambert",
    nextAction: "Suivi vendredi",
    createdAt: "2026-04-18",
    lastContact: "2026-04-30",
    notes: "Compare options de placement conservatrices.",
    tone: "violet",
  },
]

export const clients: Client[] = [
  {
    id: "sophie-tremblay",
    firstName: "Sophie",
    lastName: "Tremblay",
    birthDate: "1984-09-12",
    phone: "+1 514 555 0132",
    email: "sophie.tremblay@example.ca",
    address: "215 rue Beaubien Est, Montreal, QC",
    occupation: "Pharmacienne",
    employer: "Pharmacie Plateau Santé",
    income: "145 000 $",
    familySituation: "Conjointe, 2 enfants",
    dependents: 2,
    advisor: "Marie Lambert",
    status: "Actif",
    riskLevel: "Modéré",
    objectives: ["Protection familiale", "Épargne retraite", "Fonds d’urgence"],
    importantNotes: "Révision annuelle requise avant renouvellement vie.",
    nextReview: "2026-05-18",
    tone: "sky",
  },
  {
    id: "karim-haddad",
    firstName: "Karim",
    lastName: "Haddad",
    birthDate: "1979-02-04",
    phone: "+1 438 555 0188",
    email: "karim.haddad@example.ca",
    address: "18 rue Notre-Dame Ouest, Laval, QC",
    occupation: "Consultant indépendant",
    employer: "Haddad Stratégie Inc.",
    income: "180 000 $",
    familySituation: "Marié",
    dependents: 1,
    advisor: "Marie Lambert",
    status: "Dossier incomplet",
    riskLevel: "Élevé",
    objectives: ["Protection revenu", "Optimisation fiscale"],
    importantNotes: "Document de profil client manquant et bénéficiaire à confirmer.",
    nextReview: "2026-05-09",
    tone: "rose",
  },
  {
    id: "nadia-moreau",
    firstName: "Nadia",
    lastName: "Moreau",
    birthDate: "1968-11-27",
    phone: "+1 450 555 0119",
    email: "nadia.moreau@example.ca",
    address: "640 boulevard de la Gare, Vaudreuil-Dorion, QC",
    occupation: "Directrice des opérations",
    employer: "Logistique Nord",
    income: "132 000 $",
    familySituation: "Célibataire",
    dependents: 0,
    advisor: "Alex Roy",
    status: "Actif",
    riskLevel: "Faible",
    objectives: ["Retraite", "Protection du capital", "Planification successorale"],
    importantNotes: "Profil conservateur, préfère les explications simples.",
    nextReview: "2026-06-03",
    tone: "emerald",
  },
]

export const tasks: CrmTask[] = [
  {
    id: "task-1",
    title: "Rappeler Antoine Leduc",
    relatedTo: "Antoine Leduc",
    relationType: "Prospect",
    dueDate: "Aujourd’hui, 10:30",
    priority: "Urgente",
    status: "En retard",
    advisor: "Marie Lambert",
  },
  {
    id: "task-2",
    title: "Envoyer formulaire profil client",
    relatedTo: "Karim Haddad",
    relationType: "Client",
    dueDate: "Aujourd’hui, 14:00",
    priority: "Haute",
    status: "À faire",
    advisor: "Marie Lambert",
  },
  {
    id: "task-3",
    title: "Préparer le rendez-vous retraite",
    relatedTo: "Nadia Moreau",
    relationType: "Client",
    dueDate: "Demain, 09:00",
    priority: "Normale",
    status: "En cours",
    advisor: "Alex Roy",
  },
]

export const activities: Activity[] = [
  {
    id: "activity-1",
    type: "Prospect créé",
    description: "Antoine Leduc ajouté depuis un appel entrant.",
    user: "Système",
    dateTime: "2026-05-02 09:12",
    relatedTo: "Antoine Leduc",
    source: "Téléphone",
  },
  {
    id: "activity-2",
    type: "Note ajoutée",
    description: "Besoin de protection familiale confirmé.",
    user: "Marie Lambert",
    dateTime: "2026-05-02 09:28",
    relatedTo: "Antoine Leduc",
    source: "CRM",
  },
  {
    id: "activity-3",
    type: "Document reçu",
    description: "Formulaire profil client reçu pour Sophie Tremblay.",
    user: "Assistant",
    dateTime: "2026-05-01 16:44",
    relatedTo: "Sophie Tremblay",
    source: "Portail",
  },
]

export const communications: Communication[] = [
  {
    id: "call-1",
    relatedTo: "Antoine Leduc",
    direction: "Entrant",
    channel: "Appel",
    dateTime: "2026-05-02 09:11",
    summary: "Appel manqué, demande d’assurance vie.",
  },
  {
    id: "sms-1",
    relatedTo: "Camille Fortin",
    direction: "Sortant",
    channel: "SMS",
    dateTime: "2026-05-01 15:07",
    summary: "Confirmation de réception du formulaire.",
  },
  {
    id: "email-1",
    relatedTo: "Nadia Moreau",
    direction: "Sortant",
    channel: "Courriel",
    dateTime: "2026-04-30 11:20",
    summary: "Préparation du rendez-vous retraite.",
  },
]

export const products: FinancialProduct[] = [
  {
    id: "product-1",
    clientId: "sophie-tremblay",
    type: "Assurance vie",
    company: "Manuvie",
    contractNumber: "MV-48291-QC",
    issueDate: "2022-06-14",
    renewalDate: "2026-06-14",
    premium: "84 $ / mois",
    coverage: "500 000 $",
    beneficiaries: "Conjoint, enfants",
    status: "En vigueur",
    estimatedCommission: "1 240 $",
  },
  {
    id: "product-2",
    clientId: "karim-haddad",
    type: "Assurance invalidité",
    company: "Canada Vie",
    contractNumber: "CV-77102-QC",
    issueDate: "2023-03-09",
    renewalDate: "2026-03-09",
    premium: "126 $ / mois",
    coverage: "6 000 $ / mois",
    beneficiaries: "Non applicable",
    status: "En vigueur",
    estimatedCommission: "980 $",
  },
  {
    id: "product-3",
    clientId: "nadia-moreau",
    type: "Fonds distincts",
    company: "iA Groupe financier",
    contractNumber: "IA-10942-QC",
    issueDate: "2021-10-22",
    renewalDate: "2026-10-22",
    premium: "125 000 $",
    coverage: "Portefeuille conservateur",
    beneficiaries: "Succession",
    status: "Actif",
    estimatedCommission: "2 150 $",
  },
]

export const documents: CrmDocument[] = [
  {
    id: "doc-1",
    title: "Formulaire profil client - Sophie Tremblay",
    relatedTo: "Sophie Tremblay",
    type: "Formulaire profil client",
    status: "Validé",
    addedAt: "2026-05-01",
  },
  {
    id: "doc-2",
    title: "Consentement - Karim Haddad",
    relatedTo: "Karim Haddad",
    type: "Consentement",
    status: "À vérifier",
    addedAt: "2026-04-30",
  },
  {
    id: "doc-3",
    title: "Illustration vie - Antoine Leduc",
    relatedTo: "Antoine Leduc",
    type: "Illustration",
    status: "Brouillon",
    addedAt: "2026-05-02",
  },
]

export const automations: AutomationRule[] = [
  {
    id: "automation-1",
    name: "Appel entrant inconnu",
    trigger: "Appel entrant non reconnu",
    actions: ["Créer prospect", "Ajouter activité", "Envoyer SMS", "Créer tâche"],
    status: "Active",
    executions: 34,
    lastRun: "2026-05-02 09:12",
  },
  {
    id: "automation-2",
    name: "Prospect créé",
    trigger: "Nouveau prospect ajouté",
    actions: ["Créer tâche de rappel", "Notifier conseiller"],
    status: "Active",
    executions: 87,
    lastRun: "2026-05-01 16:10",
  },
  {
    id: "automation-3",
    name: "Tâche en retard",
    trigger: "Échéance dépassée",
    actions: ["Notifier le conseiller", "Changer la priorité"],
    status: "Active",
    executions: 18,
    lastRun: "2026-05-02 08:00",
  },
  {
    id: "automation-4",
    name: "Client sans suivi 90 jours",
    trigger: "Aucune activité depuis 90 jours",
    actions: ["Créer rappel", "Ajouter alerte conformité"],
    status: "Brouillon",
    executions: 0,
    lastRun: "Jamais",
  },
]

export const notifications: Notification[] = [
  {
    id: "notification-1",
    label: "Nouveau prospect créé",
    description: "Antoine Leduc a été ajouté depuis un appel entrant.",
    tone: "emerald",
  },
  {
    id: "notification-2",
    label: "Tâche en retard",
    description: "Rappeler Antoine Leduc devait être fait ce matin.",
    tone: "rose",
  },
  {
    id: "notification-3",
    label: "Document reçu",
    description: "Formulaire profil client reçu pour Sophie Tremblay.",
    tone: "sky",
  },
]

export const smsTemplates = [
  "Bonjour {{prenom}}, merci pour votre demande. Je vous reviens rapidement.",
  "Bonjour {{prenom}}, voici un rappel pour notre rendez-vous de demain.",
  "Bonjour {{prenom}}, pouvez-vous téléverser le document manquant?",
]

export const emailTemplates = [
  "Suivi après appel découverte",
  "Demande de documents pour analyse",
  "Préparation de révision annuelle",
]

export const complianceAlerts = [
  "Karim Haddad: document profil client manquant",
  "Sophie Tremblay: révision annuelle à planifier",
  "Nadia Moreau: bénéficiaire à confirmer au prochain suivi",
]
