ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NEGOTIATION';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'WON';

ALTER TABLE "Lead"
ADD COLUMN IF NOT EXISTS "lostReason" TEXT,
ADD COLUMN IF NOT EXISTS "lostAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lostNote" TEXT;
