ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_READ';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_DISMISSED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAD_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAD_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LEAD_STATUS_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_DUE_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DOCUMENT_REQUIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DOCUMENT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DOCUMENT_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PRODUCT_RENEWAL_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CLIENT_REVIEW_DUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SMART_ALERT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMPLIANCE_ALERT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'AUTOMATION_EXECUTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'AUTOMATION_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_MISSED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SMS_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SYSTEM';

DO $$
BEGIN
  CREATE TYPE "NotificationPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE "NotificationStatus" AS ENUM ('UNREAD', 'READ', 'ARCHIVED', 'DISMISSED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "priority" "NotificationPriority" NOT NULL DEFAULT 'NORMAL';
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "status" "NotificationStatus" NOT NULL DEFAULT 'UNREAD';
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "actionLabel" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "actionUrl" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "entityType" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "entityId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "clientId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "leadId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "taskId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "documentId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "productId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "alertId" TEXT;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "isRead" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "dismissedAt" TIMESTAMP(3);
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Notification"
SET
  "isRead" = ("readAt" IS NOT NULL),
  "status" = CASE WHEN "readAt" IS NOT NULL THEN 'READ'::"NotificationStatus" ELSE 'UNREAD'::"NotificationStatus" END,
  "actionUrl" = COALESCE("actionUrl", "href");

CREATE INDEX IF NOT EXISTS "Notification_status_idx" ON "Notification"("status");
CREATE INDEX IF NOT EXISTS "Notification_isRead_idx" ON "Notification"("isRead");
CREATE INDEX IF NOT EXISTS "Notification_priority_idx" ON "Notification"("priority");
CREATE INDEX IF NOT EXISTS "Notification_type_idx" ON "Notification"("type");
CREATE INDEX IF NOT EXISTS "Notification_createdAt_idx" ON "Notification"("createdAt");
