ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "routingTerritories" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "routingLanguages" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "licenseNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "routingPriority" INTEGER NOT NULL DEFAULT 50;
