ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'LEAD_STATUS_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'LEAD_ARCHIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CLIENT_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'TASK_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DOCUMENT_STATUS_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PRODUCT_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PRODUCT_UPDATED';
